# Generated by Django 3.1.7 on 2021-03-04 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='商品カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='商品名')),
                ('management_code', models.CharField(max_length=100, unique=True, verbose_name='管理コード')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='本体価格')),
                ('add_tax', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100000)], verbose_name='税込価格')),
                ('release_data', models.DateField(blank=True, null=True, verbose_name='発売日')),
                ('release_flag', models.BooleanField(default=False, verbose_name='発売済み')),
                ('text', models.TextField(max_length=100000, verbose_name='説明')),
                ('image', models.ImageField(null=True, upload_to='goods', verbose_name='画像')),
                ('state_flag', models.BooleanField(default=True, verbose_name='運用状況')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodsgroup', verbose_name='商品カテゴリ')),
            ],
        ),
    ]
